Catch Gutenberg errors
If your Gutenberg query doens't return any results it would be useful to
see that instead of a bizarro stack trace :)

```
public_domains "picture of dorian grey"
Traceback (most recent call last):
  File "/Users/edsummers/.pyenv/versions/3.10.1/bin/public_domains", line 8, in <module>
    sys.exit(main())
  File "/Users/edsummers/.pyenv/versions/3.10.1/lib/python3.10/site-packages/public_domains.py", line 64, in main
    hosts = get_hosts(args.text_file, args.quiet)
  File "/Users/edsummers/.pyenv/versions/3.10.1/lib/python3.10/site-packages/public_domains.py", line 92, in get_hosts
    md_sents = nltk.tokenize.sent_tokenize(md)
  File "/Users/edsummers/.pyenv/versions/3.10.1/lib/python3.10/site-packages/nltk/tokenize/__init__.py", line 107, in sent_tokenize
    return tokenizer.tokenize(text)
  File "/Users/edsummers/.pyenv/versions/3.10.1/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1276, in tokenize
    return list(self.sentences_from_text(text, realign_boundaries))
  File "/Users/edsummers/.pyenv/versions/3.10.1/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1332, in sentences_from_text
    return [text[s:e] for s, e in self.span_tokenize(text, realign_boundaries)]
  File "/Users/edsummers/.pyenv/versions/3.10.1/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1332, in <listcomp>
    return [text[s:e] for s, e in self.span_tokenize(text, realign_boundaries)]
  File "/Users/edsummers/.pyenv/versions/3.10.1/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1322, in span_tokenize
    for sentence in slices:
  File "/Users/edsummers/.pyenv/versions/3.10.1/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1421, in _realign_boundaries
    for sentence1, sentence2 in _pair_iter(slices):
  File "/Users/edsummers/.pyenv/versions/3.10.1/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 318, in _pair_iter
    prev = next(iterator)
  File "/Users/edsummers/.pyenv/versions/3.10.1/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1395, in _slices_from_text
    for match, context in self._match_potential_end_contexts(text):
  File "/Users/edsummers/.pyenv/versions/3.10.1/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1375, in _match_potential_end_contexts
    for match in reversed(list(self._lang_vars.period_context_re().finditer(text))):
TypeError: expected string or bytes-like object
```